import { StyleSheet } from 'react-native';
import { theme as defaultTheme, Theme } from '@/theme';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    backButton: {
      padding: theme.spacing.xs,
      marginRight: theme.spacing.sm,
    },
    headerTitle: {
      ...theme.typography.subtitle,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    resetButtonText: {
      ...theme.typography.bodyMedium,
      color: theme.colors.primary,
      fontWeight: '600',
    },
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      padding: theme.spacing.lg,
      flexGrow: 1,
    },
    searchCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.dimensions.borderRadius.lg,
      padding: theme.spacing.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: theme.spacing.xl,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 4,
      elevation: 1,
    },
    label: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '600',
      marginBottom: theme.spacing.xs,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.inputBackground,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.dimensions.borderRadius.md,
      paddingHorizontal: theme.spacing.md,
      height: 52,
      marginBottom: theme.spacing.md,
    },
    inputRowFocused: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.isDark ? theme.colors.inputBackground : theme.colors.surface,
    },
    prefixContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: theme.spacing.sm,
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
      marginRight: theme.spacing.sm,
      gap: 4,
    },
    flag: {
      fontSize: 16,
    },
    prefix: {
      ...theme.typography.body,
      fontWeight: '700',
      color: theme.colors.textPrimary,
    },
    input: {
      flex: 1,
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      height: '100%',
      paddingVertical: 0,
      letterSpacing: 0.5,
    },
    clearIcon: {
      padding: theme.spacing.xs,
    },
    searchButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: theme.dimensions.borderRadius.md,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    searchButtonDisabled: {
      opacity: 0.5,
    },
    searchButtonText: {
      ...theme.typography.button,
      color: theme.colors.white,
      fontWeight: '700',
    },
    initialStateContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.dimensions.borderRadius.lg,
      padding: theme.spacing.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      marginTop: theme.spacing.sm,
    },
    initialIconWrapper: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.isDark ? theme.colors.surfaceVariant : theme.colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: theme.spacing.md,
    },
    initialTitle: {
      ...theme.typography.subtitle,
      color: theme.colors.textPrimary,
      fontWeight: '700',
      marginBottom: theme.spacing.xs,
      textAlign: 'center',
    },
    initialSubtitle: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      fontSize: 14,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: `${theme.colors.error}14`,
      borderWidth: 1,
      borderColor: `${theme.colors.error}35`,
      borderRadius: theme.dimensions.borderRadius.md,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.lg,
      gap: 10,
    },
    errorText: {
      flex: 1,
      ...theme.typography.caption,
      color: theme.colors.danger,
      lineHeight: 18,
    },
    stateContainer: {
      paddingVertical: theme.spacing.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingContainer: {
      paddingVertical: theme.spacing.xxl,
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.md,
    },
    loadingText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
    },
    notFoundContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.dimensions.borderRadius.lg,
      padding: theme.spacing.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      textAlign: 'center',
      marginTop: theme.spacing.sm,
    },
    notFoundIconWrapper: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.colors.surfaceVariant,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: theme.spacing.sm,
    },
    notFoundTitle: {
      ...theme.typography.subtitle,
      color: theme.colors.textPrimary,
      marginTop: theme.spacing.xs,
      marginBottom: theme.spacing.xs,
      fontWeight: '700',
    },
    notFoundSubtitle: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      lineHeight: 18,
    },
  });

export const styles = createStyles(defaultTheme);
